#!/usr/bin/env bash
# Generate a .env from the Bicep deployment outputs.
#   bash scripts/gen_env.sh <deployment-name>   (default: expidp)
set -euo pipefail

NAME="${1:-expidp}"
out() { az deployment sub show -n "$NAME" --query "properties.outputs.$1.value" -o tsv; }

echo "Reading outputs from deployment '$NAME'..." >&2
FOUNDRY_PROJECT=$(out foundryProjectEndpoint)
FOUNDRY_ACCOUNT=$(out foundryEndpoint)
COSMOS=$(out cosmosEndpoint)
SEARCH=$(out searchEndpoint)
BLOB=$(out blobEndpoint)
APPI=$(out appInsightsConnectionString)

cat > .env <<EOF
# Generated by scripts/gen_env.sh from deployment '$NAME' on $(date -u +%Y-%m-%dT%H:%M:%SZ)
EXPENSE_MODEL_BACKEND=foundry

AZURE_OPENAI_ENDPOINT=$FOUNDRY_ACCOUNT
FOUNDRY_PROJECT_ENDPOINT=$FOUNDRY_PROJECT
FOUNDRY_MODEL=gpt-5.4-mini
FOUNDRY_MODEL_ESCALATION=gpt-5.4

# Leave the next two EMPTY for Tier 1 (records/policy fall back to local).
AZURE_SEARCH_ENDPOINT=$SEARCH
AZURE_SEARCH_INDEX=expense-policy
COSMOS_ENDPOINT=$COSMOS
COSMOS_DATABASE=expenses
COSMOS_CONTAINER=records

BLOB_ACCOUNT_URL=$BLOB
BLOB_CONTAINER=receipts

APPLICATIONINSIGHTS_CONNECTION_STRING=$APPI

APPROVAL_LOGIC_APP_URL=
ERP_POST_URL=

AUTO_APPROVE_LIMIT=75
BASE_CURRENCY=USD
MAX_AGENT_ITERATIONS=8
EOF

echo "Wrote .env" >&2
echo "For Tier 1, blank out COSMOS_ENDPOINT and AZURE_SEARCH_ENDPOINT to use local fallbacks." >&2
